### ISSUE TITLE
[Pages] Login Page

### ISSUE THREAD

**Issue by Nikhil0789** [TaxPlanner/EasyKar.com#23]
Login Page

EazyKar makes Filing IT Returns as easy and effective as humanly possible.
•	Dedicated Support team of highly experienced experts at your disposal
•	Time-based Services that ensure timely financial planning
•	High-level privacy and absolute confidentiality
•	Highly secure servers that keep your Financial Data safe
•	Machine-Level Accuracy backed by Expert Support

Benefits of Hiring Us to File IT Online?
•	File Returns without spending tedious hours with a CA
•	Do your filing in your spare time, from literally anywhere
•	Economic Packages
•	We make Financial Concepts simple and easy for our clients
•	Highly Up-To-Date experts

**Comment by vivekmore** [comment]
I'll update 
- login 
- registration
- forgot password
- reset password

pages to say EazyKar instead of EasyKar
